### ISSUE TITLE
FtpServer uses a default 1s timeout

### ISSUE THREAD

**Issue by nielsm5** [FileSysOrg/jfileserver#17]
Hey,

I noticed that the server runnable has a 1 second timeout. We use this library extensively to test out filesystem implementations but right now each test takes a minimum of 1 second which greatly increases our build times.
https://github.com/FileSysOrg/jfileserver/blob/e1ca63bd70d74959970c4840c86de815d8e296c8/src/main/java/org/filesys/ftp/FTPServer.java#L548

Is it possible to make this value configurable?

**Comment by FileSysOrg** [comment]
Hi,

Looking at the code I think it could be changed to be a Thread.yield() call, as that loop just comes back round and waits for another socket connection at the accept().

**Comment by jkosternl** [comment]
Sounds good. Are you going to do some experiments with that suggested change, to see if that still works fine in all situations?

**Comment by FileSysOrg** [comment]
Yeah, I'll need to test it when I get a chance, see if I can get that done this week.

**Comment by jkosternl** [comment]
Did you find any time yet to verify the solution of `Thread.yield()` instead of a sleep? We'd appreciate it 😉

**Comment by FileSysOrg** [comment]
I implemented the fix and did some testing, I thought I’d checked the fix in but just checked and the fix has not been pushed to GitHub. I’m away on holiday at the moment but will be back home this weekend, I’ll get the fix pushed to GitHub, I have some other changes I’m working on for the next release but that will be a while before I’m ready to push those changes and do a new release.

**Comment by FileSysOrg** [comment]
I've just pushed the FTP server change, plus some changes to the FTP configuration I needed for testing with a Docker setup. The update is version 1.3.17.

**Comment by jkosternl** [comment]
Thanks man! The new version will be available on Maven Central? I didn't find it in Maven Central and https://www.filesys.org/maven/org/filesys/ yet.

**Comment by FileSysOrg** [comment]
Not on Maven Central yet, I need to do some juggling with versions, should be there later today hopefully.

**Comment by jkosternl** [comment]
Thanks for fixing it @FileSysOrg. It works fine for us 👍🏻

**Comment by FileSysOrg** [comment]
Ok, great, I'll close this issue
