### ISSUE TITLE
this project can support Kerberos authentication？

### ISSUE THREAD

**Issue by fengyingkong** [FileSysOrg/jfileserver#7]
if support kerberos, how to configuration?

**Comment by FileSysOrg** [comment]
What platform are you running on ?.

Kerberos should be available unless you are using Android, the required JGSS classes are not available in the Java core so only NTLM is available.

--
Gary K. Spencer
***@***.***

**Comment by fengyingkong** [comment]
I have a standalone kdc and would like to dock it

**Comment by fengyingkong** [comment]
Does jfileserver have kdc?

**Comment by FileSysOrg** [comment]
There are instructions for setting up Kerberos authentication for the JFileServer here - https://www.filesys.org/wiki/index.php/Configuring_Kerberos/AD_Authentication_For_The_SMB_Server

**Comment by fengyingkong** [comment]
thank you very much.
